config/routes.rb
News::Application.routes.draw do

  get 'log_in' => 'sessions#new', as: 'log_in'
  get 'log_out' => 'sessions#destroy', as:'log_out'
  resources :sessions

  namespace :admin do
    resources :articles
  end

  get 'sign_up' => 'users#new', as: 'sign_up'
  resources :users

  root to: 'home#index'
  get '/columns', to: 'columns#index'
  get '/columns/:id', to: 'columns#show'
  get '/articles/:id', to: "articles#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :columns, :join_table => :columns_articles
  validates :title, :summary, presence: true
  validates :status, inclusion: { in: %w(draft published banned),
    message: "%{value} is not a valid status" }

  scope :published, -> { where(status: 'published') }
  scope :draft, -> { where(status: 'draft') }
  scope :banned, -> { where(status: 'banned') }

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :columns
  validates :name, presence: true, uniqueness: true
  validates_associated :columns
end

app/models/column.rb
class Column < ActiveRecord::Base
  belongs_to :channel
  has_and_belongs_to_many :articles, :join_table => :columns_articles
  validates :name, presence: true, uniqueness: true
  validates_associated :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  before_save :encrypt_password

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :authorize_admin
  layout 'admin/application'
  def index
    @articles = Article.all
  end

  def show
    @article = Account.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
    p @article.columns
    if @article
      render 'admin/articles/edit'
    else
      halt 404
    end

  end

  def create
    @user = Article.new(article_params)
  end


  private

  def article_params
    params.require(:article).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin?
    User.find(session[:user_id]).role == 'admin' if session[:user_id]
  end

  def authorize_admin
    redirect_to log_in_url, alert: "Not authorized" if !admin?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
    halt 404 if @article.status != "published"
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController

  def index
    @columns = Column.includes(:articles)
    @articles = @columns.map(&:articles).map(&:published).flatten.uniq
  end

  def show
    @columns = Column.limit(10)
    @column = Column.find(params[:id])
    @articles = @column.articles.published
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/views/admin/articles/_form.html.slim
fieldset class='controls-group'

  div class='controls span2'
    = f.label "标题", :class => 'control-label'
    = f.text_field :title

  div class='controls span2'
    = f.label "摘要", :class => 'control-label'
    = f.text_area :summary

  div class='controls span2'
    = f.label "状态", :class => 'control-label'
    = f.select :status, [['草稿','draft'],['发布','published'],['取消','banned']]

  div class='controls span2'
    = f.label "栏目", :class => 'control-label'
    - for col in Column.find(:all)
      div
        = check_box_tag "article[column_ids][]", col.id, @article.columns.include?(col)
        = col.name

  div class='controls'
    = f.label "内容", :class => 'control-label'
    = f.text_area :content

div class="form-actions"
  = f.submit "save", :class => 'btn btn-primary'
  |&nbsp;
  = f.submit "save_and_continue", :class => 'btn btn-info', :name => 'save_and_continue'
  |&nbsp;
  = link_to "cancel", admin_articles_path, :class => 'btn'

app/views/admin/articles/edit.html.slim
ul class="nav nav-tabs"
  li = link_to "index", admin_articles_path
  li = link_to "new", new_admin_article_path
  li class="active" = link_to "edit", edit_admin_article_path

div class="tabs-content"
  = form_for [:admin, @article], url: {action: "edit"}, html: {class: 'form-horizontal' }do |f|
    = render partial: 'admin/articles/form', locals: {f: f}

app/views/admin/articles/index.html.slim
ul class="nav nav-tabs"
  li class="active" = link_to "index", admin_articles_path
  li = link_to "new", new_admin_article_path

div class="tabs-content"
  table class="table table-striped table-hover table-condensed" id="list"
    thead
      tr
        th class='header list-menu'
        th class='header' 标题

    tbody
      -@articles.each do |article|
        tr class='list-row'
          td class='list-column list-selectable' = check_box_tag 'article_ids[]', :value => article.id, :class => 'list-selectable-checkbox'
          td class='list-column' = article.title
          td class='list-column list-row-action'
            div class='list-row-action-wrapper'
              = link_to "edit", edit_admin_article_path(article.id), :rel => :tooltip, :title => "edit", :class => 'list-row-action-wrapper-link'
              = link_to "trash", :rel => :tooltip, :title => "delete article", :class => 'list-row-action-delete-one list-row-action-wrapper-link'
              div class='popover list-row-action-popover-delete-one left'
                div class='arrow'
                h3 class='popover-title' = "delete article"
                div class='popover-content'
                  - form_tag admin_article_path(article.id), :method => :delete do
                    = submit_tag :delete, :class =>'list-row-action-popover-delete-one-btn btn btn-danger btn-small'
                    div class='btn btn-small cancel' = "cancel"

app/views/articles/index.html.slim
ul class="nav nav-tabs"
  -@columns.each do |col|
    li class = ((@column.name == col.name)?'active':'')
      = link_to "#{col.name}", "/columns/#{col.name}/"

div class="article-list"
  ul
    -@articles.each do |article|
      li
        div class="article-list-img"
          = image_tag(article.img_url)
        div class="article-list-url"
          = link_to article.title, "/columns/#{@column.name}/articles/#{article.id}"

app/views/articles/show.html.slim
h1 =@article.title
div class="article-content"
  h2 =@article.summary
  p =@article.content

app/views/columns/index.html.slim
ul class="nav nav-tabs"
  li.active
    = link_to "index", "/columns"
  -@columns.each do |col|
    li
      = link_to "#{col.name}", "/columns/#{col.id}/"

div class="article-list"
  ul
    -@articles.each do |article|
      li
        div class="article-list-img"
          = image_tag(article.img_url)
        div class="article-list-url"
          = link_to article.title, "/articles/#{article.id}"

app/views/columns/show.html.slim
ul class="nav nav-tabs"
  li
    = link_to "index", "/columns"
  -@columns.each do |col|
    li class = ((@column.name == col.name)?'active':'')
      = link_to "#{col.name}", "/columns/#{col.id}/"

div class="article-list"
  ul
    -@articles.each do |article|
      li
        div class="article-list-img"
          = image_tag(article.img_url)
        div class="article-list-url"
          = link_to article.title, "/articles/#{article.id}"

app/views/layouts/application.html.slim
doctype 5
html lang='en'
  head
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    meta content='text/html; charset=utf-8' http-equiv='Content-Type'
    meta name='viewport' content='width=device-width,initial-scale=1'
    link href='http://fonts.googleapis.com/css?family=Varela' rel='stylesheet'
    = stylesheet_link_tag 'bootstrap', 'application'

  body
    div class='navbar navbar-fixed-top'
      div class='navbar-inner'
        div class='container'

          ul class='nav navbar-nav pull-right'
            li
              div
                - if current_user
                  | #{current_user.email}
                  |  |
                  | #{link_to "Log out", log_out_path}
                - else
                  = link_to "Sign up", sign_up_path
                  | or
                  | #{link_to "Log in", log_in_path}

          ul class='nav navbar-nav pull-left'

    div class='container main'
      div class='main-wrapper'
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash#{name}"

        div class='row' = yield
        div class='main-wrapper-push'

    footer
      div class='footer-wrapper container'
        p class='pull-left'
          ' Copyright &copy; #{Time.now.year} Your Site -
        ul class='pull-right footer-links'

    =javascript_include_tag 'jquery-1.9.0.min', 'bootstrap.min' , 'application'

app/views/users/new.html.slim
h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      h2 Form is invalid
      ul
        - for message in @user.errors.full_messages
          li= message
  p
    = f.label :email
    br/
    = f.text_field :email
  p
    = f.label :password
    br/
    = f.password_field :password
  p
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  p.button= f.submit